// <auto-generated />
using System;
using DiveDeepEF.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiveDeepEF.Migrations
{
    [DbContext(typeof(DiveDeepEFContext))]
    partial class DiveDeepEFContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DiveDeepEF.Models.Bookings.BasketItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("EquipmentId");

                    b.ToTable("BasketItems");
                });

            modelBuilder.Entity("DiveDeepEF.Models.Bookings.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CostumerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CostumerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("DiveDeepEF.Models.Equipments.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EquipmentType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<float>("PricePerDay")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Equipments");

                    b.HasDiscriminator<string>("EquipmentType").HasValue("Equipment");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DiveDeepEF.Models.Equipments.BCD", b =>
                {
                    b.HasBaseType("DiveDeepEF.Models.Equipments.Equipment");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("BCD");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Scubapro",
                            PricePerDay = 125f,
                            Model = "Navigator Lite",
                            Size = "S, M, L"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Scubapro",
                            PricePerDay = 140f,
                            Model = "Glide",
                            Size = "S, M, L"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Scubapro",
                            PricePerDay = 200f,
                            Model = "Hydros Pro",
                            Size = "S, M, L"
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Seac",
                            PricePerDay = 145f,
                            Model = "Modular",
                            Size = "S, M, L"
                        });
                });

            modelBuilder.Entity("DiveDeepEF.Models.Equipments.Fins", b =>
                {
                    b.HasBaseType("DiveDeepEF.Models.Equipments.Equipment");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Equipments", t =>
                        {
                            t.Property("Model")
                                .HasColumnName("Fins_Model");

                            t.Property("Size")
                                .HasColumnName("Fins_Size");
                        });

                    b.HasDiscriminator().HasValue("Fins");

                    b.HasData(
                        new
                        {
                            Id = 5,
                            Brand = "Scubapro",
                            PricePerDay = 50f,
                            Model = "Jet Fin",
                            Size = "XS, S, M, L, XL"
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Scubapro",
                            PricePerDay = 50f,
                            Model = "GO Travel",
                            Size = "XS, S, M, L, XL"
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Scubapro",
                            PricePerDay = 60f,
                            Model = "Seawing Supernova",
                            Size = "XS, S, M, L, XL"
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Seac",
                            PricePerDay = 50f,
                            Model = "Propulsion",
                            Size = "XS, S, M, L, XL"
                        },
                        new
                        {
                            Id = 9,
                            Brand = "Seac",
                            PricePerDay = 50f,
                            Model = "ALA",
                            Size = "XS, S, M, L, XL"
                        },
                        new
                        {
                            Id = 10,
                            Brand = "Fourth Element",
                            PricePerDay = 75f,
                            Model = "Tech",
                            Size = "XS, S, M, L, XL"
                        },
                        new
                        {
                            Id = 11,
                            Brand = "Fourth Element",
                            PricePerDay = 80f,
                            Model = "Rec Fin",
                            Size = "XS, S, M, L, XL"
                        });
                });

            modelBuilder.Entity("DiveDeepEF.Models.Equipments.Mask", b =>
                {
                    b.HasBaseType("DiveDeepEF.Models.Equipments.Equipment");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Equipments", t =>
                        {
                            t.Property("Model")
                                .HasColumnName("Mask_Model");
                        });

                    b.HasDiscriminator().HasValue("Mask");

                    b.HasData(
                        new
                        {
                            Id = 12,
                            Brand = "Scubapro",
                            PricePerDay = 50f,
                            Model = "Ghost"
                        },
                        new
                        {
                            Id = 13,
                            Brand = "Scubapro",
                            PricePerDay = 60f,
                            Model = "D-Mask"
                        },
                        new
                        {
                            Id = 14,
                            Brand = "Scubapro",
                            PricePerDay = 50f,
                            Model = "Spectra Mini"
                        },
                        new
                        {
                            Id = 15,
                            Brand = "Scubapro",
                            PricePerDay = 75f,
                            Model = "Crystal VU"
                        },
                        new
                        {
                            Id = 16,
                            Brand = "Fourth Element",
                            PricePerDay = 75f,
                            Model = "Scout Enhance"
                        },
                        new
                        {
                            Id = 17,
                            Brand = "Tusa",
                            PricePerDay = 75f,
                            Model = "Element"
                        });
                });

            modelBuilder.Entity("DiveDeepEF.Models.Equipments.RegulatorSet", b =>
                {
                    b.HasBaseType("DiveDeepEF.Models.Equipments.Equipment");

                    b.Property<string>("FirstStage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Octopus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondStage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("RegulatorSet");

                    b.HasData(
                        new
                        {
                            Id = 18,
                            Brand = "Scubapro",
                            PricePerDay = 125f,
                            FirstStage = "MK25 EVO",
                            Octopus = "R105",
                            SecondStage = "S600"
                        },
                        new
                        {
                            Id = 19,
                            Brand = "Scubapro",
                            PricePerDay = 100f,
                            FirstStage = "MK17 EVO",
                            Octopus = "R095",
                            SecondStage = "C370"
                        },
                        new
                        {
                            Id = 20,
                            Brand = "Scubapro",
                            PricePerDay = 150f,
                            FirstStage = "MK25 EVO BT",
                            Octopus = "S270",
                            SecondStage = "A700 Carbon BT"
                        });
                });

            modelBuilder.Entity("DiveDeepEF.Models.Equipments.Suit", b =>
                {
                    b.HasBaseType("DiveDeepEF.Models.Equipments.Equipment");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Thickness")
                        .HasColumnType("float");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Equipments", t =>
                        {
                            t.Property("Model")
                                .HasColumnName("Suit_Model");

                            t.Property("Size")
                                .HasColumnName("Suit_Size");
                        });

                    b.HasDiscriminator().HasValue("Suit");

                    b.HasData(
                        new
                        {
                            Id = 21,
                            Brand = "Scubapro",
                            PricePerDay = 100f,
                            Gender = "Men/Women",
                            Model = "Definition",
                            Size = "XS, S, M, L, XL",
                            Thickness = 3.0,
                            Type = "Wetsuit"
                        },
                        new
                        {
                            Id = 22,
                            Brand = "Scubapro",
                            PricePerDay = 100f,
                            Gender = "Men/Women",
                            Model = "Definition",
                            Size = "XS, S, M, L, XL",
                            Thickness = 5.0,
                            Type = "Wetsuit"
                        },
                        new
                        {
                            Id = 23,
                            Brand = "Scubapro",
                            PricePerDay = 100f,
                            Gender = "Men/Women",
                            Model = "Definition",
                            Size = "XS, S, M, L, XL",
                            Thickness = 7.0,
                            Type = "Wetsuit"
                        },
                        new
                        {
                            Id = 24,
                            Brand = "Waterproof",
                            PricePerDay = 100f,
                            Gender = "Men/Women",
                            Model = "W5",
                            Size = "XS, S, M, L, XL",
                            Thickness = 3.5,
                            Type = "Wetsuit"
                        },
                        new
                        {
                            Id = 25,
                            Brand = "Fourth Element",
                            PricePerDay = 120f,
                            Gender = "Men/Women",
                            Model = "Proteus",
                            Size = "XS, S, M, L, XL",
                            Thickness = 5.0,
                            Type = "Wetsuit"
                        },
                        new
                        {
                            Id = 26,
                            Brand = "Scubapro",
                            PricePerDay = 300f,
                            Gender = "Men/Women",
                            Model = "Exodry 4.0",
                            Size = "XS, S, M, L, XL",
                            Type = "Drysuit"
                        },
                        new
                        {
                            Id = 27,
                            Brand = "Waterproof",
                            PricePerDay = 320f,
                            Gender = "Men/Women",
                            Model = "D7 Evo",
                            Size = "XS, S, M, L, XL",
                            Type = "Drysuit"
                        },
                        new
                        {
                            Id = 28,
                            Brand = "Santi",
                            PricePerDay = 350f,
                            Gender = "Men/Women",
                            Model = "E.Lite Plus",
                            Size = "XS, S, M, L, XL",
                            Type = "Drysuit"
                        });
                });

            modelBuilder.Entity("DiveDeepEF.Models.Equipments.Tank", b =>
                {
                    b.HasBaseType("DiveDeepEF.Models.Equipments.Equipment");

                    b.Property<int>("Volume")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Tank");

                    b.HasData(
                        new
                        {
                            Id = 29,
                            Brand = "Scubapro",
                            PricePerDay = 150f,
                            Volume = 5
                        },
                        new
                        {
                            Id = 30,
                            Brand = "Scubapro",
                            PricePerDay = 160f,
                            Volume = 10
                        },
                        new
                        {
                            Id = 31,
                            Brand = "Scubapro",
                            PricePerDay = 170f,
                            Volume = 12
                        },
                        new
                        {
                            Id = 32,
                            Brand = "Scubapro",
                            PricePerDay = 180f,
                            Volume = 15
                        });
                });

            modelBuilder.Entity("DiveDeepEF.Models.Bookings.BasketItem", b =>
                {
                    b.HasOne("DiveDeepEF.Models.Bookings.Booking", "Booking")
                        .WithMany("BasketItems")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiveDeepEF.Models.Equipments.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("DiveDeepEF.Models.Bookings.Booking", b =>
                {
                    b.Navigation("BasketItems");
                });
#pragma warning restore 612, 618
        }
    }
}
